### ISSUE TITLE
Decide on the IaC directory name

### ISSUE THREAD

**Issue by stefaniuk** [nhs-england-tools/repository-template#84]
Terraform is our tool of choice for IaC.

Some common directory names for IaC are:

- `terraform`: This name clearly communicates what's the content of the directory and that the code is written in Terraform. However, it's less descriptive about the nature of the content, i.e. that it's infrastructure code. 
- `infrastructure`: This alternative name is more broad, it indicates that the contained code is for managing infrastructure. It describes the intent. On a larger projects not all IaC is Terraform. It is usually accompanied by OCI image definitions, Kubernetes deployment scripts, Python and shell scripts as a glue code.
- `infra`: Shorten version of the above but it just feels lazy.
- `iac`: Not very common at all but still an option.

**Comment by timrickwood** [comment]
I would vote for _Infrastructure_. It is the most descriptive and most portable name. Failing that _iac_ although like _infra_ that too feels a bit lazy. I would vote down _terraform_ because that feels too opinionated about the choice of tech and as you say where would you store code that relates to the infrastructure that is not written in terraform.

**Comment by jens-kursch-NHSD** [comment]
I'd vote for _infrastructure_. A generic name seems like the right name it also leaves space for projects to add additional subdivisions of IoC technologies.
